gcccore/5.4.0(13):ERROR:150: Module 'gcccore/5.4.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/5.4.0(13):ERROR:102: Tcl command execution failed: conflict gcccore

binutils/2.26-gcccore-5.4.0(11):ERROR:150: Module 'binutils/2.26-gcccore-5.4.0' conflicts with the currently loaded module(s) 'binutils/2.28-gcccore-6.4.0'
binutils/2.26-gcccore-5.4.0(11):ERROR:102: Tcl command execution failed: conflict binutils

gcccore/5.4.0(13):ERROR:150: Module 'gcccore/5.4.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/5.4.0(13):ERROR:102: Tcl command execution failed: conflict gcccore

binutils/2.26-gcccore-5.4.0(11):ERROR:150: Module 'binutils/2.26-gcccore-5.4.0' conflicts with the currently loaded module(s) 'binutils/2.28-gcccore-6.4.0'
binutils/2.26-gcccore-5.4.0(11):ERROR:102: Tcl command execution failed: conflict binutils

gcccore/5.4.0(13):ERROR:150: Module 'gcccore/5.4.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/5.4.0(13):ERROR:102: Tcl command execution failed: conflict gcccore

binutils/2.26-gcccore-5.4.0(11):ERROR:150: Module 'binutils/2.26-gcccore-5.4.0' conflicts with the currently loaded module(s) 'binutils/2.28-gcccore-6.4.0'
binutils/2.26-gcccore-5.4.0(11):ERROR:102: Tcl command execution failed: conflict binutils

python/2.7.12-intel-2016b(13):ERROR:150: Module 'python/2.7.12-intel-2016b' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/2.7.12-intel-2016b(13):ERROR:102: Tcl command execution failed: conflict python

zlib/1.2.8-intel-2016b(15):ERROR:150: Module 'zlib/1.2.8-intel-2016b' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.8-intel-2016b(15):ERROR:102: Tcl command execution failed: conflict zlib

python/2.7.12-intel-2016b(13):ERROR:150: Module 'python/2.7.12-intel-2016b' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/2.7.12-intel-2016b(13):ERROR:102: Tcl command execution failed: conflict python

gcc/8.3.0(24):ERROR:150: Module 'gcc/8.3.0' conflicts with the currently loaded module(s) 'gcc/6.4.0-2.28'
gcc/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcc

cuda/10.1.243-gcc-8.3.0(28):ERROR:150: Module 'cuda/10.1.243-gcc-8.3.0' conflicts with the currently loaded module(s) 'cuda/9.0.176'
cuda/10.1.243-gcc-8.3.0(28):ERROR:102: Tcl command execution failed: conflict cuda

openmpi/3.1.4-gcccuda-2019b(22):ERROR:150: Module 'openmpi/3.1.4-gcccuda-2019b' conflicts with the currently loaded module(s) 'openmpi/2.1.2-gcc-6.4.0-2.28'
openmpi/3.1.4-gcccuda-2019b(22):ERROR:102: Tcl command execution failed: conflict openmpi

openblas/0.3.7-gcc-8.3.0(22):ERROR:150: Module 'openblas/0.3.7-gcc-8.3.0' conflicts with the currently loaded module(s) 'openblas/0.2.20-gcc-6.4.0-2.28'
openblas/0.3.7-gcc-8.3.0(22):ERROR:102: Tcl command execution failed: conflict openblas

fftw/3.3.8-gompic-2019b(24):ERROR:150: Module 'fftw/3.3.8-gompic-2019b' conflicts with the currently loaded module(s) 'fftw/3.3.7-gompi-2018a'
fftw/3.3.8-gompic-2019b(24):ERROR:102: Tcl command execution failed: conflict fftw

scalapack/2.0.2-gompic-2019b(24):ERROR:150: Module 'scalapack/2.0.2-gompic-2019b' conflicts with the currently loaded module(s) 'scalapack/2.0.2-gompi-2018a-openblas-0.2.20'
scalapack/2.0.2-gompic-2019b(24):ERROR:102: Tcl command execution failed: conflict scalapack

gcc/8.3.0(24):ERROR:150: Module 'gcc/8.3.0' conflicts with the currently loaded module(s) 'gcc/6.4.0-2.28'
gcc/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcc

cuda/10.1.243-gcc-8.3.0(28):ERROR:150: Module 'cuda/10.1.243-gcc-8.3.0' conflicts with the currently loaded module(s) 'cuda/9.0.176'
cuda/10.1.243-gcc-8.3.0(28):ERROR:102: Tcl command execution failed: conflict cuda

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

h5py/2.10.0-fosscuda-2019b-python-3.7.4(26):ERROR:150: Module 'h5py/2.10.0-fosscuda-2019b-python-3.7.4' conflicts with the currently loaded module(s) 'h5py/2.6.0-intel-2016b-python-2.7.12-hdf5-1.8.17'
h5py/2.10.0-fosscuda-2019b-python-3.7.4(26):ERROR:102: Tcl command execution failed: conflict h5py

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

hwloc/1.11.12-gcccore-8.3.0(38):ERROR:150: Module 'hwloc/1.11.12-gcccore-8.3.0' conflicts with the currently loaded module(s) 'hwloc/1.11.8-gcccore-6.4.0'
hwloc/1.11.12-gcccore-8.3.0(38):ERROR:102: Tcl command execution failed: conflict hwloc

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

sqlite/3.29.0-gcccore-8.3.0(22):ERROR:150: Module 'sqlite/3.29.0-gcccore-8.3.0' conflicts with the currently loaded module(s) 'sqlite/3.22.0-foss-2018a'
sqlite/3.29.0-gcccore-8.3.0(22):ERROR:102: Tcl command execution failed: conflict sqlite

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

bzip2/1.0.8-gcccore-8.3.0(30):ERROR:150: Module 'bzip2/1.0.8-gcccore-8.3.0' conflicts with the currently loaded module(s) 'bzip2/1.0.6-foss-2018a'
bzip2/1.0.8-gcccore-8.3.0(30):ERROR:102: Tcl command execution failed: conflict bzip2

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

python/3.7.4-gcccore-8.3.0(47):ERROR:150: Module 'python/3.7.4-gcccore-8.3.0' conflicts with the currently loaded module(s) 'python/3.7.2-foss-2018a'
python/3.7.4-gcccore-8.3.0(47):ERROR:102: Tcl command execution failed: conflict python

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

gcccore/8.3.0(24):ERROR:150: Module 'gcccore/8.3.0' conflicts with the currently loaded module(s) 'gcccore/6.4.0'
gcccore/8.3.0(24):ERROR:102: Tcl command execution failed: conflict gcccore

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

zlib/1.2.11-gcccore-8.3.0(26):ERROR:150: Module 'zlib/1.2.11-gcccore-8.3.0' conflicts with the currently loaded module(s) 'zlib/1.2.11-foss-2018a'
zlib/1.2.11-gcccore-8.3.0(26):ERROR:102: Tcl command execution failed: conflict zlib

  WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/home/n9455647/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorboard 2.3.0 requires requests<3,>=2.21.0, which is not installed.
tensorflow 2.3.1 requires h5py<2.11.0,>=2.10.0, but you'll have h5py 2.6.0 which is incompatible.
tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
tensorflow 2.3.1 requires six>=1.12.0, but you'll have six 1.10.0 which is incompatible.
tensorboard 2.3.0 requires setuptools>=41.0.0, but you'll have setuptools 40.6.2 which is incompatible.
Traceback (most recent call last):
  File "lstm_test.py", line 8, in <module>
    import EncoderFactory
  File "/home/n9455647/PPM_Evaluation/Stability-Experiments/benchmark_interpretability/PPM_Stability/EncoderFactory.py", line 1, in <module>
    from transformers.StaticTransformer import StaticTransformer
  File "/home/n9455647/PPM_Evaluation/Stability-Experiments/benchmark_interpretability/PPM_Stability/transformers/StaticTransformer.py", line 1, in <module>
    from sklearn.base import TransformerMixin
  File "/home/n9455647/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 80, in <module>
    from .base import clone
  File "/home/n9455647/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    import numpy as np
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/pkg/suse12/software/python/2.7.12-intel-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libiomp5.so: cannot open shared object file: No such file or directory
